### PR TITLE
Add isSupported

### PR DESCRIPTION
**Pull request by Roemer**
Add a method to allow checking if the device supports backlight.
Checks for backlight support on method calls and not on initialize.

### CODE REVIEW

**Comment by Roemer** [comment]
Would fix #7

**Comment by pimterry** [comment]
Makes sense, looks great to me, thanks for the PR @Roemer! I'll put this out in a new release in just a minute.

**Comment by Roemer** [comment]
Awesome thanks! I'm using your library in a raspi/touch-based media player for children (https://github.com/Roemer/TouchMediaPlayer). The prototype is already in use and I hope to publish it within the next 1-2 weeks.

**Comment by pimterry** [comment]
Awesome! Sounds like a great project, glad to hear that this module is helping you out :smile:

**Pull request merged**
